package uk.ac.nott.cs.g53dia.multidemo;

import java.util.LinkedList;

/**
 * This class is a model to store the plan generated by the deliberative layer
 * it holds the steps needed to take, the distance the agent will travel
 * and the size of the task the agent will complete
 */
public class PlanModel {

	LinkedList<PositionTuple> plan;
	int distance;
	int taskSize;
	int tankerID;
	
	public PlanModel(LinkedList<PositionTuple> plan, int distance, int taskSize, int tankerID) {
		this.plan = plan;
		this.distance = distance;
		this.taskSize = taskSize;
		this.tankerID = tankerID;
	}
}
